apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: {{.Values.namespace.name}}
  labels:
    app: techtrends
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: {{.Values.replicaCount}}
  selector: # defines how the Deployment finds which Pods to manage.
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
        - name: techtrends
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - containerPort: {{.Values.containerPort}}
          resources:
            limits:
              cpu: {{.Values.resources.limits.cpu}}
              memory: {{.Values.resources.limits.memory}}
            requests:
              cpu: {{.Values.resources.requests.cpu}}
              memory: {{.Values.resources.requests.memory}}
          readinessProbe:
            httpGet:
              path: {{.Values.readinessProbe.path}}
              port: {{.Values.readinessProbe.port}}
          livenessProbe:
            httpGet:
              path: {{.Values.livenessProbe.path}}
              port: {{.Values.livenessProbe.port}}