apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{.Values.namespace.name}}
  labels:
    app: techtrends
spec:
  ports:
    - port: {{.Values.service.port}}
      protocol: {{.Values.service.protocol}}
      targetPort: {{if not .Values.service.targetPort}}{{.Values.service.port}}{{else}}{{.Values.service.targetPort}}{{end}}
  type: {{.Values.service.type}}
  selector:
    app: techtrends
