name: TechTrends - Package with Docker
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            agvaeducation/techtrends
          tags: |
            type=semver,pattern={{major}}.{{minor}}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.docker_username}}
          password: ${{secrets.docker_access_token}}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: project
          push: true
          tags: ${{ steps.meta.outputs.tags }}

