name: TechTrends - Package with Docker
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Increment Step Patch
        id: increment-step-patch
        uses: Benbentwo/increment-semver@master
        with:
          version-level: '-p'
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.docker_username}}
          password: ${{secrets.docker_access_token}}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: project
          push: true
          tags: agvaeducation/techtrends:${{steps.increment-step-patch.outputs.version}}
