name: TechTrends - Package with Docker
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.docker_access_token}}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.docker_username}}
          password: ${{secrets.docker_access_token}}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: project
          push: true
          tags: ${{steps.buildnumber.outputs.build_number}}